"""Detection signals for Provenance Guard.

Two genuinely independent signals, as required by the spec:
  1. classify_with_llm()   -> semantic signal (Groq)
  2. stylometric_score()   -> structural signal (pure Python, no deps)

Both return a float in [0, 1]: the estimated probability that the supplied
text is AI-generated. Higher = more AI-like.
"""

import json
import os
import re
import statistics

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

GROQ_MODEL = "llama-3.3-70b-versatile"

_groq_client = None


def _get_groq_client():
    global _groq_client
    if _groq_client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError(
                "GROQ_API_KEY is not set. Copy .env.example to .env and add your key."
            )
        _groq_client = Groq(api_key=api_key)
    return _groq_client


LLM_PROMPT_TEMPLATE = """You are a careful, skeptical AI-text detection assistant. \
Assess the following piece of writing and estimate the probability that it was \
primarily generated by an AI language model rather than written by a human.

Consider: generic or hedge-heavy phrasing ("it is important to note", "furthermore"), \
lack of specific concrete/sensory detail, overly uniform sentence structure, and \
unnaturally "balanced" argumentation as signs of AI generation. Consider concrete \
personal detail, irregular phrasing, idiosyncratic word choice, and informal voice \
as signs of human writing. Remember that formal human writing (academic, legal, \
technical) can share surface features with AI writing -- judge holistically, not \
just on formality.

Respond with ONLY a JSON object, no other text, in exactly this shape:
{{"ai_probability": <float between 0.0 and 1.0>, "reasoning": "<one sentence>"}}

Text to assess:
\"\"\"
{text}
\"\"\"
"""


def _parse_llm_json(raw: str) -> dict:
    """Groq sometimes wraps JSON in markdown fences despite instructions; strip those."""
    cleaned = raw.strip()
    cleaned = re.sub(r"^```(json)?", "", cleaned).strip()
    cleaned = re.sub(r"```$", "", cleaned).strip()
    return json.loads(cleaned)


def classify_with_llm(text: str) -> dict:
    """Signal 1: ask Groq to assess AI-vs-human authorship.

    Returns a dict: {"score": float in [0,1], "reasoning": str}.
    On any failure (missing key, API error, bad JSON), falls back to a neutral
    0.5 score so a single flaky API call degrades gracefully instead of
    crashing the whole pipeline -- the stylometric signal still carries the
    submission, and the result will simply skew toward "uncertain".
    """
    try:
        client = _get_groq_client()
        completion = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[
                {"role": "user", "content": LLM_PROMPT_TEMPLATE.format(text=text)}
            ],
            temperature=0.0,
            max_tokens=200,
        )
        raw = completion.choices[0].message.content
        parsed = _parse_llm_json(raw)
        score = float(parsed.get("ai_probability", 0.5))
        score = max(0.0, min(1.0, score))
        return {"score": score, "reasoning": parsed.get("reasoning", ""), "error": None}
    except Exception as exc:  # noqa: BLE001 - we want to degrade gracefully on *any* failure
        return {"score": 0.5, "reasoning": None, "error": str(exc)}


_WORD_RE = re.compile(r"[A-Za-z']+")
_SENTENCE_SPLIT_RE = re.compile(r"(?<=[.!?])\s+")


def _split_sentences(text: str) -> list[str]:
    sentences = [s.strip() for s in _SENTENCE_SPLIT_RE.split(text.strip()) if s.strip()]
    return sentences if sentences else [text.strip()]


def _sentence_length_cv_score(sentences: list[str]) -> float:
    """Lower variance in words-per-sentence -> more uniform -> more AI-like."""
    lengths = [len(_WORD_RE.findall(s)) for s in sentences if _WORD_RE.findall(s)]
    if len(lengths) < 2:
        return 0.5  # not enough sentences to measure variance meaningfully
    mean_len = statistics.mean(lengths)
    if mean_len == 0:
        return 0.5
    stdev_len = statistics.pstdev(lengths)
    cv = stdev_len / mean_len  # coefficient of variation
    # Empirically, human prose often has CV > ~0.5; very uniform AI prose often < ~0.3.
    # Map CV in [0, 0.6] down to an AI-likelihood score in [1, 0] (clamped).
    ai_likeness = 1.0 - (cv / 0.6)
    return max(0.0, min(1.0, ai_likeness))


def _type_token_ratio_score(words: list[str]) -> float:
    """Lower vocabulary diversity (more repetition) -> more AI-like."""
    if not words:
        return 0.5
    lowered = [w.lower() for w in words]
    ttr = len(set(lowered)) / len(lowered)
    # Short texts naturally have high TTR; longer AI-generated text tends to
    # plateau lower than human text of comparable length. Map TTR in
    # [0.4, 0.9] down to AI-likelihood in [1, 0] (clamped).
    ai_likeness = 1.0 - ((ttr - 0.4) / 0.5)
    return max(0.0, min(1.0, ai_likeness))


def _long_word_density_score(words: list[str]) -> float:
    """Higher density of long (7+ char) words -> more uniformly formal -> more AI-like."""
    if not words:
        return 0.5
    long_words = [w for w in words if len(w) >= 7]
    density = len(long_words) / len(words)
    # Map density in [0.05, 0.30] up to AI-likelihood in [0, 1] (clamped).
    ai_likeness = (density - 0.05) / 0.25
    return max(0.0, min(1.0, ai_likeness))


def stylometric_score(text: str) -> dict:
    """Signal 2: pure-Python structural heuristics.

    Returns a dict with the combined score plus each sub-metric, so callers
    (and the audit log / debugging) can see where the signal comes from.
    """
    sentences = _split_sentences(text)
    words = _WORD_RE.findall(text)

    sentence_cv_score = _sentence_length_cv_score(sentences)
    ttr_score = _type_token_ratio_score(words)
    long_word_score = _long_word_density_score(words)

    combined = (sentence_cv_score + ttr_score + long_word_score) / 3.0

    return {
        "score": combined,
        "sentence_length_cv_score": sentence_cv_score,
        "type_token_ratio_score": ttr_score,
        "long_word_density_score": long_word_score,
    }
